---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  name: pdnd-interop-uservice-user-registry-management
  namespace: {{ .Release.Namespace }}
spec:
  rules:
    - host: usrreg-d-aks-192f1515.hcp.northeurope.azmk8s.io
      http:
        paths:
          - path: /users
            pathType: Prefix
            backend:
              service:
                name: pdnd-interop-uservice-user-registry-management
                port: 
                  number: 8088
